/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a real install. It is checked in here so
// the scaffold is readable before dependencies are installed.
